# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: All Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: zeshue/aspnet9-jammy-ffmpeg:1.0.2
      credentials:
        username: zeshue
        password: ${{ secrets.docker_hub_password }}

    strategy:
      fail-fast: false
      matrix:
        test-suite:
          - Compression.Tests
          - Core.Tests
          - Csv.Tests
          - DeepClone.Tests
          - EFCore.Tests
          - Email.Tests
          - Excel.ClosedXml.Tests
          - Excel.Npoi.Tests
          - Excel.OpenXml.Tests
          - FastMap.Tests
          - Hangfire.Tests
          - Images.Tests
          - Media.Ffmpeg.Tests
          - Office.Common.Tests
          - Sql.Common.Tests
          - SubsetModelBinder.Tests
          - Web.Api.Tests
          - Web.Aws.S3.Tests
          - Web.Common.Tests
          - Web.Ftp.Tests
          - Web.Interface.Tests
          - Web.Jwt.Tests
          - Web.Middleware.Tests
          - Web.Requests.Tests
          - Word.OpenXml.Tests

    steps:
      - uses: actions/checkout@v4

      - name: Get Curl
        run: apt-get update && apt-get install -y curl

      - name: Add LibreOffice
        if: matrix.test-suite == 'Office.Common.Tests'
        run: apt-get install libreoffice -y

      - name: Get Libre Office Version
        if: matrix.test-suite == 'Office.Common.Tests'
        run: soffice --version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x.x

      - name: Add Fonts
        if: matrix.test-suite == 'Office.Common.Tests'
        run: apt-get update && apt-get install -y fonts-dejavu fonts-liberation fonts-ubuntu

      - name: Update Font Cache
        if: matrix.test-suite == 'Office.Common.Tests'
        run: fc-cache -f

      - name: Add OptiPng
        if: matrix.test-suite == 'Images.Tests'
        run: apt-get install -y optipng

      - name: Add GifSicle
        if: matrix.test-suite == 'Images.Tests'
        run: apt-get install -y gifsicle

      - name: Add JpegOptim
        if: matrix.test-suite == 'Images.Tests'
        run: apt-get install -y jpegoptim

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./${{ matrix.test-suite }}

      - name: Build
        run: dotnet build --no-restore
        working-directory: ./${{ matrix.test-suite }}

      - name: Test
        run: dotnet test --verbosity normal -p:TestTfmsInParallel=false --collect:"XPlat Code Coverage" --results-directory ./coverage -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile="**/*.g.cs;**/obj/**;**/bin/**"
        working-directory: ./${{ matrix.test-suite }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.test-suite }}/coverage/**/coverage.cobertura.xml
          flag-name: ${{ matrix.test-suite }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
